name: Check markdown links
on:
  push:
    branches:
    - test
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Link Checker
      id: link_checker
      uses: ./
      with:
        args: -v -r *	
    - name: Check output
      run: echo ${{ steps.link_checker.outputs.result }}
    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_TITLE: Link Checker Report
        ISSUE_CONTENT_FILEPATH: ./link-checker/out.md
        ISSUE_LABELS: report, automated issue
        ISSUE_ASSIGNEES: peter-evans
